# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: []
  pull_request:
    branches: []

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ["release"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install xmllint
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          install.packages("devtools")
          devtools::install_github("stackOcean-official/shinify", host = "https://api.github.com")
        shell: Rscript {0}
      - name: Test linear
        run: |
          source("jumpstart/linear_regression.R")
        shell: Rscript {0}
